name: test action

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
    
      - name: EC2 test
        env:
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.SSH_HOST  }}
            USER_NAME : ${{ secrets.SSH_USER  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && 
          chmod 600 private_key
          
          ssh -o StrictHostKeyChecking=off -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /data/diwos-backend &&
            sudo git checkout main &&
            sudo git fetch --all &&
            sudo git reset --hard origin/main &&
            sudo git pull origin main &&
            sudo sh update.sh
          '
